### ISSUE TITLE
Triangle.v11.suo file should be excluded from the repo

### ISSUE THREAD

**Issue by teisnet** [wo80/Triangle#1]
First, thanks for this patch, very useful!
Just a note, Visual Studio .suo files contains user specific settings and it is recommended not to be included in the repository (https://msdn.microsoft.com/en-us/library/bb165909.aspx).

regards Teis

**Comment by wo80** [comment]
Fixed in e696eac76dd0eeb39efd636fdf0d1f65bbf4d5b6.
