### ISSUE TITLE
Non-GUI version of Triangle?

### ISSUE THREAD

**Issue by mirkov** [wo80/Triangle#13]
(I could not find a better place for my question except for the Issues tab. I realize that this may be outside of what the developer cares for, and please feel free to ignore, or tell me where it is better to post this question).

I would like to compile the software on Windows via MSYS2 for purely command-line interaction for processing files, i.e., no GUI.  The GUI part is causing me grief in loading (undefined reference to WinMain, or if I use the SDL2 library, undefined reference to SDL_Main).

Can you tell me which part of the code handles the graphics, so that I can try and remove it?

**Comment by wo80** [comment]
This repository does not contain any GUI or SDL/OpenGL stuff.

**Comment by mirkov** [comment]
Thank you - I will look for the source of my errors on my side.
