### ISSUE TITLE
Could you migrate Triangle.NET from Codeplex to Github

### ISSUE THREAD

**Issue by licg9999** [wo80/Triangle#17]
Hello wo80, 

> CodePlex is going read-only starting November 27th.

As a Unity3D user, I think Triangle.NET is really a good library to do mesh generation.
And, could you please migrate Triangle.NET and keep it maintained on Github? So that U3D programmers, like me, could have a place to follow or fork & merge to help develop the library.

Sincerely, 

https://triangle.codeplex.com/

**Comment by wo80** [comment]
I have no plans to move Triangle.NET to Github right now. But there are forks already, for example https://github.com/eppz/Triangle.NET

**Comment by licg9999** [comment]
OK, fine.
