### ISSUE TITLE
Integrate libtriangle with Triangle directory-wise

### ISSUE THREAD

**Issue by jzarl** [wo80/Triangle#19]
I think that moving the triangle-api files out of the directory `examples/libtriangle` into the directory `Triangle` would both simplify build scripts and make it clear that triangle-api is the recommended way to use triangle rather than just a wrapper for the examples.

With the cmake files as they are now I didn't want to disturb too much for the existing VS solution files (also, I needed some working solution fast without too much hassle). If it's ok to remove the `.sln` files, I can prepare a pull request implementing the proposed changes.

**Comment by wo80** [comment]
Yes, go ahead. Moving libtriangle out of the examples directory and removing the Visual Studio project files is ok.
