### ISSUE TITLE
Try this test file? 

### ISSUE THREAD

**Issue by samyuchao** [wo80/Triangle#25]
[1.zip](https://github.com/wo80/Triangle/files/1641743/1.zip)
![image](https://user-images.githubusercontent.com/10825626/35082879-1039e4a8-fc57-11e7-933a-35535683bcc1.png)

**Comment by samyuchao** [comment]
Anyone know the issue ?  how to fix?

**Comment by wo80** [comment]
1. This is not the right place to ask about Triangle.NET.
2. You are probably running out of floating point precision. Try normalizing the coordinates (for example, removing the first two digits from the x and the first three digits from the y-coordinates worked for me).

**Comment by samyuchao** [comment]
Thank you for the answer.  so, which version you are using?
Is there binary file(*.exe) can be downloaded?

**Comment by samyuchao** [comment]
I'm failed to build the source code with Visual studio 2017 on window 10
