### ISSUE TITLE
what about this file to trianglate? 

### ISSUE THREAD

**Issue by samyuchao** [wo80/Triangle#26]
Infinite loop with Triangle.Net

[1.zip](https://github.com/wo80/Triangle/files/1646089/1.zip)

**Comment by samyuchao** [comment]
Do you know any difference between triangle and triangle.net?

**Comment by wo80** [comment]
Again: this is **NOT** the right place to ask about Triangle.NET.

Both Triangle.NET and the original C code will end up in an infinite loop for the given polygon and there's not much you can do about it. Your polygon has a lot of overlapping, nearly collinear segments, which Triangle cannot handle well.
