### ISSUE TITLE
triangle.net

### ISSUE THREAD

**Issue by adriaanpfeiffer** [wo80/Triangle#34]
Hello,

I know this isn't the best place to ask as it is no triangle (c++) issue. But do you still have plans to put triangle.net under your github repo's?

**Comment by wo80** [comment]
Not planning to do so. There's a fork available at https://github.com/eppz/Triangle.NET

**Comment by adriaanpfeiffer** [comment]
OK, yes I saw it. eppz is not maintaining it though as he states that he is not the original author and it is just a mere copy for his own good. Doesn't matter. Anyways, thanks for a great library (still use it with great pleasure).
