### ISSUE TITLE
Building shared libs with Visual Studio fails

### ISSUE THREAD

**Issue by wo80** [wo80/Triangle#35]
@jzarl 

The change made to `src/Triangle/CMakeLists.txt` in commit https://github.com/wo80/Triangle/commit/ff37e513d206e25052ec7178062adc86693addfc makes the CMake build fail with Visual Studio 2017:
```
Error LNK1181	cannot open input file 'Release\triangle.lib'   triangle-api
Error LNK1181	cannot open input file '..\..\Triangle\Release\triangle-api.lib'   triangle-test
Error LNK1181	cannot open input file '..\..\Triangle\Release\triangle-api.lib'   triangle-cli
```
Adding the `SHARED` back to `add_library(triangle-api ...` solves the issue.

Any idea why this happens?

**Comment by jzarl** [comment]
Assuming there are no stale build files in the Visual Studio project I don't really have a clue.
Where does VS put the triangle.lib file? I guess this one is created correctly, but triangle-api.lib is not?

I'll see if I can find a Windows PC so that I can recreate the problem. In the meantime, maybe a workaround like this would work:

````cmake
if (MSVC)
  add_library(triangle-api SHARED ...)
else()
  add_library(triangle-api ...)
endif()
````

**Comment by wo80** [comment]
Here's the CMake config:
![cmake-gui](https://user-images.githubusercontent.com/1840402/39329634-3ad28d6a-499f-11e8-99b8-b1f527e6eb9b.png)

* The `build/Release` folder does not contain any files.
* The `build/Triangle/Release` folder contains a `triangle.dll` file, but the DLL has no exports (as expected)

So, the `triangle` project should actually compile to `triangle.lib`, which would then be linked into `triangle-api.dll`. But instead the `triangle.dll` gets created ...

**Comment by jzarl** [comment]
That's interesting. I assumed from the error message that BUILD_SHARED_LIBS was set to false. If that's enabled then there should be no .lib files involved (at least as far as I understand the Windows linking process).

Just out of curiosity: if you build with BUILD_SHARED_LIBS disabled, do you get the same error?

**Comment by wo80** [comment]
Building with `BUILD_SHARED_LIBS` disabled I get no errors. I do get `triangle.lib`, `triangle-api.lib` and `triangle.exe`, but no DLL (as expected).

I think, the best way to solve this, is to add `STATIC` to the `triangle` library in src/Triangle/CMakeLists.txt:
```
# triangle ist the legacy interface:
add_library(triangle STATIC
```
This gives the correct results for both `BUILD_SHARED_LIBS` enabled and disabled (at least with Visual Studio).

**Comment by jzarl** [comment]
I'm still at a loss why VS produces this error, but making triangle static is ok for me...

**Comment by wo80** [comment]
My guess: since no functions are exported form the triangle library, no lib file is created (just a useless DLL, containing no exports).

I'll make the change to the CMake file and close this issue.
