### ISSUE TITLE
Concave Polygons

### ISSUE THREAD

**Issue by pfdx44** [wo80/Triangle#36]
I try to triangulate concave polygons but it gives convex polygon triangulation. 

Where am I wrong? 

Could you please give me any idea?

![adsiz](https://user-images.githubusercontent.com/202415/39604052-52c855aa-4f33-11e8-99ef-f2665109dc9d.png)

**Comment by wo80** [comment]
Have you forgot to add the boundary segments to triangleio input or to add the -p switch (behavior->poly = 1)?

**Comment by pfdx44** [comment]
It was "-c" switch. Thank you.
