### ISSUE TITLE
voronoi face issure

### ISSUE THREAD

**Issue by jianchunhuang** [wo80/Triangle#38]
wo80,

I am trying to use TriangleNet.Voronoi.BoundedVoronoi to create a boundedVoronoi and I found that some of the boundary faces has infinite number of edges. 

In the example that I attached, I use a 10X10 square to create a triangle mesh and each side of the square has 3 node.  All faces are correct except the 3 faces at the boundary.  

Thanks for your help.

_image deleted due to oversize (edit by wo80)_

**Comment by jianchunhuang** [comment]
It looks that this happens when the circumcenter is located outside of the domain.  It I change the postProcess() in TriangleNet.Voronoi to 

        private void PostProcess()
        {
            foreach (var edge in rays)
            {
                var twin = edge.twin;

                var v1 = (TVertex)edge.face.generator;
                var v2 = (TVertex)twin.face.generator;

                double dir = predicates.CounterClockwise(v1, v2, edge.origin);

                HandleCase1(edge, v1, v2);

                //if (dir <= 0)
                //{
                //    HandleCase1(edge, v1, v2);
                //}
                //else
                //{
                //    HandleCase2(edge, v1, v2);
                //}
            }
        }

I got the following diagram.

_image deleted due to oversize (edit by wo80)_

**Comment by wo80** [comment]
1. This is not the right place to ask about Triangle.NET. Post issues over at [eppz/Triangle.NET](https://github.com/eppz/Triangle.NET/issues)
2. Your images are absurdly large (10240 x 5760). Resize them before uploading!
3. Is your mesh **conforming** Delaunay (i.e. did you set `ConstraintOptions.ConformingDelaunay = true`).

I'm closing this one. If point 3 doesn't fix the issue, re-open it (see point 1) and please include the mesh data (you can export the mesh using `TriangleNet.IO.TriangleFormat.Write(mesh, filename)`).
