### ISSUE TITLE
Crash on VS2013

### ISSUE THREAD

**Issue by zoharl3** [wo80/Triangle#5]
The app crashes when built with Visual Studio Ultimate 2013 (using the example A.poly), at:

vertexloop[0] = x;

Also, how do you use aCute?

**Comment by zoharl3** [comment]
I found the problem. It's an x64 problem. (void *) on x32 is 4 bytes while on x64 it's 8 bytes. sizeof(long)=4 is the same on both. So all the x64 pointer alignment calculations overflow. To remedy that, need to replace all (not exactly all, since there might be a conversion somewhere to double - unrelated to pointers - that might overflow) "unsigned long" with "unsigned long long".

**Comment by wo80** [comment]
Never tried to build it as x64, but I think it would be a nice addition. Feel free to fork and make a pull request.

Regarding aCute: the code is used by default, see line 13643. Take a look at their website for more information (https://www.cise.ufl.edu/~ungor/aCute/quality.html).

**Comment by zoharl3** [comment]
Oh, I didn't realize that you actually incorporated their algo, I thought you just added their memory pool or something (although, I don't remember seeing it in use). That's interesting.

At this point, I just did a global text replace of "unsigned long" with "unsigned long long", and it worked on two examples. So, it's a bit dirty, and not quite tested. But I'll consider forking in the future (if no one would do it by then).

**Comment by wo80** [comment]
Fixed in commit 6a87bb006c3a0de22615c041b89ed7a1f8013bfb
