### ISSUE TITLE
bug in .off or .ele file?

### ISSUE THREAD

**Issue by cmoha** [wo80/Triangle#6]
First, I'd like to thank you for you this repo.
Second thing I want to discuss is a a contradiction I found in `.ele` file and `.off` file;
the  `.off` file contains the indices of nodes but in `.ele` file the indices of nodes is subtracted by 1 for example
in `.ele` file

```
285  3  0
   1      44    32    72
   2      18    47    21
   3      19    52    61
   4      52    11    55
   5      79    68    51
   6      23    22    20
   7      55    20     8
   8      66   156   153
```

but in `.off` file

```
 3     43    31    71
 3     17    46    20
 3     18    51    60
 3     51    10    54
 3     78    67    50
 3     22    21    19
 3     54    19     7
 3     65   155   152
```

 and I'm not sure which one gives the correct order

**Comment by wo80** [comment]
I've never used OFF output. Triangle starts node numbering at index 1 (unless you use the -z switch). Maybe the OFF format requires indices starting at 0. So both might be correct.

**Comment by cmoha** [comment]
Thank you, one final question.
Can you extend the library to be used in managed code, C# for example.
My abilities in C programming won't help me doing that.
Thank you again.

**Comment by wo80** [comment]
You can build the DLL and use [P/Invoke](https://msdn.microsoft.com/en-us/library/aa288468.aspx) to call the native functions. I've already done this with Triangle and I will publish the project here on GitHub sometime this year.

Another option might be my managed version available on Codeplex: [Triangle.NET](http://triangle.codeplex.com/)

**Comment by cmoha** [comment]
Thank you for the input, I'll take a look at your project later.
I looked at the example int the link above, and all thing is seems fine except for passing input parameters. Can you send me a snippets of your implementation until you upload it here? or send it to me @ civilms@outlook.com if you don't want to expose your code. I really need it for a research purpose.

**Comment by wo80** [comment]
I will have a look at the code this weekend and then contact you by e-mail.
