### ISSUE TITLE
help for using in C++ in Visual Studio

### ISSUE THREAD

**Issue by hduonggithub** [wo80/Triangle#9]
Hi there,

I hope my question this time will not bother you much.

I have successfully compiled the project in Visual Studio 2012. The output is Triangle.lib and Triangle.dll.

I have successfully tested in Visual Studio 2012 by the main file in C (tricall.c) by adding directory of header files to Additional Include Directories, directory of the Triangle.lib in Library Directories, and Triangle.lib in Linker/Input. Everything works fine.

My problem is want to use this library in my C++ project. When I change the filename of tricall.c to tricall.cpp, it results so many errors that i think c++ compiler does not c format. I have tried to put the triangle.h as below in my main file, tricall.cpp, but it still did not work.

extern "C"
{
# include "triangle.h"

} 

I appreciate if you can help me to figure out this issue or give some advises.

Thank you very much indeed.

**Comment by wo80** [comment]
Please download the latest commit. Calling the DLL from C++ code works fine for me.

If you still can't compile, please post the errors you get.

**Comment by hduonggithub** [comment]
Thank you for your reply.

I have downloaded latest files, opened your Traingle.sln and compiled successfully in a compiler version of V110 to have Triangle.dll and Triangle.lib. (I will try to upload my project in my github and you can see more details). Thanks!

Inside the project folder, I created a C project (test_triangle) with a main file named main.c. Setting up include directories, linker directories and linker input. I got it compiled and run successfully, but I still see many many errors as below even though it still works. 

Then i changed the main.c file to main.cpp, it cannot compiled and new errors include all errors in the previous main.c project.

A. Here is an error list when i use main.c (still compiled and run OK )
A.1 Output Tab:
1>------ Rebuild All started: Project: test_triangle, Configuration: Debug Win32 ------
1>  main.c
1>  triangle.c
1>  Generating Code...
1>     Creating library C:\thirdparty\vs2012\Trianglevc\test_triangle\Debug\test_triangle.lib and object C:\thirdparty\vs2012\Trianglevc\test_triangle\Debug\test_triangle.exp
1>  test_triangle.vcxproj -> C:\thirdparty\vs2012\Trianglevc\test_triangle\Debug\test_triangle.exe
**========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========**

A.2 Error List
    1   IntelliSense: declaration is incompatible with "<error-type> report" (declared at line 181) c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  40
    2   IntelliSense: variable "io" is not a type name  c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  40
    3   IntelliSense: variable "markers" is not a type name c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  40
    4   IntelliSense: variable "reporttriangles" is not a type name c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  40
    5   IntelliSense: variable "reportneighbors" is not a type name c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  40
    6   IntelliSense: variable "reportsegments" is not a type name  c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  40
    7   IntelliSense: variable "reportedges" is not a type name c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  41
    8   IntelliSense: variable "reportnorms" is not a type name c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  41
    9   IntelliSense: expected a '{'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  42
    10  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  205
    11  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  205
    12  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  213
    13  IntelliSense: expected a ')'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  213
    14  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  215
    15  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  216
    16  IntelliSense: expected a ')'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  216
    17  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  217
    18  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  218
    19  IntelliSense: expected a ')'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  218
    20  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  224
    21  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  224
    22  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  225
    23  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  225
    24  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  226
    25  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  226
    26  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  231
    27  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  231
    28  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  233
    29  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  233
    30  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  234
    31  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  234
    32  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  236
    33  IntelliSense: expected a ';'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  236
    34  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  241
    35  IntelliSense: expected a ')'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  241
    36  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  243
    37  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  244
    38  IntelliSense: expected a ')'    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  244
    39  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  248
    40  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  249
    41  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  250
    42  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  251
    43  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  252
    44  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  253
    45  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  254
    46  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  255
    47  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  256
    48  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  257
    49  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  258
    50  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  259
    51  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  260
    52  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  261
    53  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  262
    54  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  263
    55  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  264
    56  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  265
    57  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  266
    58  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  267
    59  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  268
    60  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  269
    61  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  270
    62  IntelliSense: this declaration has no storage class or type specifier   c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  272
    63  IntelliSense: expected a declaration    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  273
    64  IntelliSense: expected a declaration    c:\thirdparty\vs2012\Trianglevc\test_triangle\test_triangle\main.c  274
..........

---

B. Here is an error list when i change to main.cpp in the same project (cannot compile)
1>------ Rebuild All started: Project: test_triangle, Configuration: Debug Win32 ------
1>  triangle.c
1>  main.cpp
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(40): error C2065: 'io' : undeclared identifier
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(40): error C2065: 'markers' : undeclared identifier
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(40): error C2065: 'reporttriangles' : undeclared identifier
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(40): error C2065: 'reportneighbors' : undeclared identifier
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(40): error C2065: 'reportsegments' : undeclared identifier
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(41): error C2065: 'reportedges' : undeclared identifier
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(41): error C2065: 'reportnorms' : undeclared identifier
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(42): error C2448: 'report' : function-style initializer appears to be a function definition
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(181): error C3861: 'report': identifier not found
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(216): error C3861: 'report': identifier not found
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(218): error C3861: 'report': identifier not found
1>c:\thirdparty\vs2012\trianglevc\test_triangle\test_triangle\main.cpp(244): error C3861: 'report': identifier not found
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by wo80** [comment]
1. You can ignore the IntelliSense errors (not present in VS2015).
2. Make sure the declaration of the `report` method looks like this:

```
void report(struct triangulateio *io, int markers, int reporttriangles, int reportneighbors,
        int reportsegments, int reportedges, int reportnorms)
```

The original _tricall.c_ file doesn't use ANSI function prototypes, so you have to fix that.

**Comment by hduonggithub** [comment]
OK I have replaced the report function and it works for both with main.c or main.cpp

Thank you very much for your help!
